blank_issues_enabled: true
contact_links:
  - name: 文档
    url: https://github.com/tangsangsimida/EasyKiConverter_QT/tree/master/docs
    about: 查看项目文档，可能已经有您需要的答案
  - name: 讨论
    url: https://github.com/tangsangsimida/EasyKiConverter_QT/discussions
    about: 在讨论区与其他用户交流
  - name: 报告 Bug
    url: https://github.com/tangsangsimida/EasyKiConverter_QT/issues/new?template=bug_report.md
    about: 报告您发现的问题
  - name: 功能建议
    url: https://github.com/tangsangsimida/EasyKiConverter_QT/issues/new?template=feature_request.md
    about: 建议新功能或改进
  - name: 提问
    url: https://github.com/tangsangsimida/EasyKiConverter_QT/issues/new?template=question.md
    about: 询问关于项目使用的问题
